apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: justice-gov-uk-demo
  namespace: justice-gov-uk-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justice-gov-uk-demo
  minReplicas: 6
  maxReplicas: 18
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
