---
dory:
  dnsmasq:
    enabled: true
    domains:
      - domain: docker
        address: 127.0.0.1
    container_name: dory_dnsmasq
    port: 53
    kill_others: true
    service_start_delay: 5
    image: tripox/dory-dnsmasq:latest
  nginx_proxy:
    enabled: true
    container_name: dory_dinghy_http_proxy
    https_enabled: false
    ssl_certs_dir: ''
    port: 80
    tls_port: 443
    image: taybenlor/dinghy-http-proxy:latest
  resolv:
    enabled: true
    nameserver: 127.0.0.1
    port: 53
