name: Design system deployment

on:
  push:
    branches:
    # TODO: Change to 'main' once tested and released
      - 'frontend-rework'
    paths:
      - 'public/app/frontend/**'


jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    environment: design-system
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: './public/app/frontend'
    steps:
      - name: 'Manual checkout'
        uses: actions/checkout@v4

      - name: 'Set up Node'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 'Install Node'
        run: npm install

      - name: 'Build Node'
        shell: bash
        run: npm run build-storybook

      - name: "Configuring AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.S3_ROLE_TO_ASSUME }}
          role-session-name: "justice-gov-uk-design-system-${{ github.run_number }}"
          aws-region: "eu-west-2"

      - name: Deploy to S3
        shell: bash
        run: aws s3 sync ./public/app/frontend/storybook-static s3://$AWS_S3_BUCKET --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
