name: "Justice.Gov.UK -- Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: image
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_demo:
    name: "Demo"
    needs: [image, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, deploy_staging]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

