name: Deploy to MoJ Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy_dev:
    name: "Deploy / Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  deploy_staging:
    name: "Deploy / Staging"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging

  deploy_production:
    name: "Deploy / Production"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

