name: "Justice.Gov.UK -- Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'frontend-rework'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  modsec_config:
    name: "Modsec"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/modsec-config.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [image, modsec_config]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.development }}
    secrets: inherit

  # TODO: Temporary job whilst we deploy the fe rework to demo for testing; remove when fully merged
  build_design_system_image:
    name: "FE rework image"
    if: github.event.ref == 'refs/heads/frontend-rework'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_demo:
    name: "Demo"
    # revert needs to [image, deploy_dev] and if to " "/heads/main once fe rework is merged to main
    # TODO: remember to update demo environment allowed branches on GitHub too
    needs: [build_design_system_image, modsec_config]
    if: github.event.ref == 'refs/heads/frontend-rework'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.build_design_system_image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.demo }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, modsec_config, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.staging }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, modsec_config, deploy_staging]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.production }}
    secrets: inherit

