name: Deploy to MoJ Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
    secrets: inherit

  deploy_staging:
    name: "Staging"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit

  deploy_demo:
    name: "Demo"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: deploy_staging
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit

