name: "Justice.Gov.UK -- Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  modsec_config:
    name: "Modsec"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/modsec-config.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [image, modsec_config]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.development }}
    secrets: inherit

  deploy_demo:
    name: "Demo"
    needs: [image, modsec_config, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.demo }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, modsec_config, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.staging }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, modsec_config, deploy_staging]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
      modsec_config: ${{ needs.modsec_config.outputs.production }}
    secrets: inherit

