name: "Justice.Gov.UK -- Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'frontend-rework'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Identify if any changes have been made to the theme or frontend folders
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: dorny/paths-filter@v3 #https://github.com/dorny/paths-filter
        id: filter
        with:
          filters: |
            theme:
              - 'public/app/backend/justice/**'
            frontend:
              - 'public/app/frontend/**'

  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: image
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  build_design_system_image:
    name: "FE rework image"
    if: github.event.ref == 'refs/heads/frontend-rework'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_design_system:
    name: "Design system"
    needs: [changes, build_design_system_image]
    if: ${{ needs.changes.outputs.frontend == 'true' }} # only run if there's been a change to the frontend files
    uses: ./.github/workflows/deploy.yml
    with:
      environment: design-system
      registry: ${{ needs.build_design_system_image.outputs.registry }}
    secrets: inherit

  deploy_demo:
    name: "Demo"
    needs: build_design_system_image
    if: github.event.ref == 'refs/heads/frontend-rework'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.build_design_system_image.outputs.registry }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, deploy_staging]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

