name: "Get Modsec config."

on:
  workflow_call:
    outputs:
      development:
        description: "Modsec Config. for Development"
        value: ${{ jobs.modsec_config.outputs.development }}
      demo:
        description: "Modsec Config. for Development"
        value: ${{ jobs.modsec_config.outputs.demo }}
      staging:
        description: "Modsec Config. for Development"
        value: ${{ jobs.modsec_config.outputs.staging }}
      production:
        description: "Modsec Config. for Production"
        value: ${{ jobs.modsec_config.outputs.production }}

jobs:
  modsec_config:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      development: ${{ steps.get-config.outputs.development }}
      production: ${{ steps.get-config.outputs.production }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: 'ministryofjustice/moj-modsec-rules'
          ref: 'justice-gov-uk-initial-rules'
          # This is a fine-grained PAT, it's scoped to the moj-modsec private repository with 2 permissions: 
          # Content: Read-only.
          # Metadata: Read-only.
          token: ${{ secrets.MOJ_MODSEC_RO_PAT }}
      - name: "Get & format Modsec config."
        id: get-config
        uses: mikefarah/yq@master
        with:
          cmd: |
            DEVELOPMENT=$(./bin/get-data.sh -b justice-gov-uk -e development -i 6 -f "data/php-wordpress.yml")
            DEMO=$(       ./bin/get-data.sh -b justice-gov-uk -e demo        -i 6 -f "data/php-wordpress.yml")
            STAGING=$(    ./bin/get-data.sh -b justice-gov-uk -e staging     -i 6 -f "data/php-wordpress.yml")
            PRODUCTION=$( ./bin/get-data.sh -b justice-gov-uk -e production  -i 6 -f "data/php-wordpress.yml")

            {
                echo 'development<<EOF'
                echo "$DEVELOPMENT"
                echo EOF
            } >> $GITHUB_OUTPUT

            {
                echo 'demo<<EOF'
                echo "$DEMO"
                echo EOF
            } >> $GITHUB_OUTPUT

            {
                echo 'staging<<EOF'
                echo "$STAGING"
                echo EOF
            } >> $GITHUB_OUTPUT

            {
                echo 'production<<EOF'
                echo "$PRODUCTION"
                echo EOF
            } >> $GITHUB_OUTPUT
